INSERT INTO companyiex(symbol, companyName, exchange, industry, sector, CEO, securityName) VALUES('PG', 'Procter & Gamble Co.', 'New York Stock Exchange','Household/Personal Care', 'Consumer Non-Durables', 'David S. Taylor', 'Procter & Gamble Company'),
('VZ', 'Verizon Communications, Inc.', 'New York Stock Exchange','Major Telecommunications', 'Communications', 'Hans Erik Vestberg', 'Verizon Communications Inc.'),
('MRK', 'Merck & Co., Inc.', 'New York Stock Exchange','Pharmaceuticals: Major', 'Health Technology', 'Kenneth C. Frazier', 'Merck & Co., Inc.'),
('CMCSA', 'Comcast Corp.', 'NASDAQ','Cable/Satellite TV', 'Consumer Services', 'Brian L. Roberts', 'Comcast Corporation Class A'),
('ORCL', 'Oracle Corp.', 'New York Stock Exchange','Packaged Software', 'Technology Services', 'Safra Ada Catz', 'Oracle Corporation'),
('NKE', 'NIKE, Inc.', 'New York Stock Exchange','Apparel/Footwear', 'Consumer Non-Durables', 'Mark G. Parker', 'NIKE, Inc. Class B'),
('AMGN', 'Amgen, Inc.', 'NASDAQ','Biotechnology', 'Health Technology', 'Robert A. Bradway', 'Amgen Inc.'),
('SBUX', 'Starbucks Corp.', 'NASDAQ','Restaurants', 'Consumer Services', 'Kevin Johnson', 'Starbucks Corporation'),
('DHR', 'Danaher Corp.', 'New York Stock Exchange','Medical Specialties', 'Health Technology', 'Thomas Patrick Joyce', 'Danaher Corporation'),
('BMY', 'Bristol-Myers Squibb Co.', 'New York Stock Exchange','Pharmaceuticals: Major', 'Health Technology', 'Giovanni Caforio', 'Bristol-Myers Squibb Company'),
('SYK', 'Stryker Corp.', 'New York Stock Exchange','Medical Specialties', 'Health Technology', 'Kevin A. Lobo', 'Stryker Corporation'),
('MS', 'Morgan Stanley', 'New York Stock Exchange','Investment Banks/Brokers', 'Finance', 'James Patrick Gorman', 'Morgan Stanley'),
('CELG', 'Celgene Corp.', 'NASDAQ','Biotechnology', 'Health Technology', 'Mark J. Alles', 'Celgene Corporation'),
('CI', 'Cigna Corp.', 'New York Stock Exchange','Managed Health Care', 'Health Services', 'David Michael Cordani', 'Cigna Corporation'),
('TGT', 'Target Corp.', 'New York Stock Exchange','Specialty Stores', 'Retail Trade', 'Brian C. Cornell', 'Target Corporation'),
('AEP', 'American Electric Power Co., Inc.', 'New York Stock Exchange','Electric Utilities', 'Utilities', 'Nicholas K. Akins', 'American Electric Power Company, Inc.'),
('BIIB', 'Biogen, Inc.', 'NASDAQ','Biotechnology', 'Health Technology', 'Michel Vounatsos', 'Biogen Inc.'),
('FISV', 'Fiserv, Inc.', 'NASDAQ','Data Processing Services', 'Technology Services', 'Jeffery W. Yabuki', 'Fiserv, Inc.'),
('DAL', 'Delta Air Lines, Inc.', 'New York Stock Exchange','Airlines', 'Transportation', 'Edward Herman Bastian', 'Delta Air Lines, Inc.'),
('MFC', 'Manulife Financial Corp.', 'New York Stock Exchange','Life/Health Insurance', 'Finance', 'Roy Gori', 'Manulife Financial Corporation'),
('ALL', 'The Allstate Corp.', 'New York Stock Exchange','Property/Casualty Insurance', 'Finance', 'Thomas Joseph Wilson', 'Allstate Corporation'),
('TRI', 'Thomson Reuters Corp.', 'New York Stock Exchange','Financial Publishing/Services', 'Commercial Services', 'James C. Smith', 'Thomson Reuters Corporation'),
('HSY', 'The Hershey Co.', 'New York Stock Exchange','Food: Specialty/Candy', 'Consumer Non-Durables', 'Michele G. Buck', 'Hershey Company'),
('IQV', 'IQVIA Holdings, Inc.', 'New York Stock Exchange','Services to the Health Industry', 'Health Services', 'Ari Bousbib', 'IQVIA Holdings Inc'),
('LUV', 'Southwest Airlines Co.', 'New York Stock Exchange','Airlines', 'Transportation', 'Gary C. Kelly', 'Southwest Airlines Co.'),
('RACE', 'Ferrari NV', 'New York Stock Exchange','Motor Vehicles', 'Consumer Durables', 'Louis C. Camilleri', 'Ferrari NV'),
('DFS', 'Discover Financial Services', 'New York Stock Exchange','Regional Banks', 'Finance', 'Roger C. Hochschild', 'Discover Financial Services'),
('MCK', 'McKesson Corp.', 'New York Stock Exchange','Medical Distributors', 'Distribution Services', 'Brian Scott Tyler', 'McKesson Corporation'),
('ALXN', 'Alexion Pharmaceuticals, Inc.', 'NASDAQ','Biotechnology', 'Health Technology', 'Ludwig N. Hantson', 'Alexion Pharmaceuticals, Inc.'),
('FNMA', 'Federal National Mortgage Association', 'US OTC','Finance/Rental/Leasing', 'Finance', 'Hugh R. Frater', 'Federal National Mortgage Association'),
('CERN', 'Cerner Corp.', 'NASDAQ','Information Technology Services', 'Technology Services', 'Brent Shafer', 'Cerner Corporation'),
('HIG', 'The Hartford Financial Services Group, Inc.', 'New York Stock Exchange','Multi-Line Insurance', 'Finance', 'Christopher J. Swift', 'Hartford Financial Services Group, Inc.'),
('SNPS', 'Synopsys, Inc.', 'NASDAQ','Packaged Software', 'Technology Services', 'Aart J. de Geus / Chi-Foon Chan', 'Synopsys, Inc.'),
('KEYS', 'Keysight Technologies, Inc.', 'New York Stock Exchange','Electronic Equipment/Instruments', 'Electronic Technology', 'Ronald S. Nersesian', 'Keysight Technologies Inc'),
('CPRT', 'Copart, Inc.', 'NASDAQ','Miscellaneous Commercial Services', 'Commercial Services', 'A. Jayson Adair', 'Copart, Inc.'),
('CDNS', 'Cadence Design Systems, Inc.', 'NASDAQ','Packaged Software', 'Technology Services', 'Lip Bu Tan', 'Cadence Design Systems, Inc.'),
('CHD', 'Church & Dwight Co., Inc.', 'New York Stock Exchange','Household/Personal Care', 'Consumer Non-Durables', 'Matthew Thomas Farrell', 'Church & Dwight Co., Inc.'),
('CDW', 'CDW Corp.', 'NASDAQ','Information Technology Services', 'Technology Services', 'Christine A. Leahy', 'CDW Corp.'),
('HEI', 'HEICO Corp.', 'New York Stock Exchange','Aerospace & Defense', 'Electronic Technology', 'Laurans A. Mendelson', 'HEICO Corporation'),
('OMC', 'Omnicom Group, Inc.', 'New York Stock Exchange','Advertising/Marketing Services', 'Commercial Services', 'John D. Wren', 'Omnicom Group Inc'),
('LH', 'Laboratory Corp. of America Holdings', 'New York Stock Exchange','Services to the Health Industry', 'Health Services', 'David P. King', 'Laboratory Corporation of America Holdings'),
('HBAN', 'Huntington Bancshares, Inc.', 'NASDAQ','Regional Banks', 'Finance', 'Stephen D. Steinour', 'Huntington Bancshares Incorporated'),
('HAS', 'Hasbro, Inc.', 'NASDAQ','Recreational Products', 'Consumer Durables', 'Brian D. Goldner', 'Hasbro, Inc.'),
('DISCA', 'Discovery, Inc.', 'NASDAQ','Cable/Satellite TV', 'Consumer Services', 'David M. Zaslav', 'Discovery, Inc. Class A'),
('HOLX', 'Hologic, Inc.', 'NASDAQ','Medical Specialties', 'Health Technology', 'Stephen P. MacMillan', 'Hologic, Inc.'),
('ALLY', 'Ally Financial, Inc.', 'New York Stock Exchange','Regional Banks', 'Finance', 'Jeffrey Jonathan Brown', 'Ally Financial Inc'),
('WRB', 'W.R. Berkley Corp.', 'New York Stock Exchange','Property/Casualty Insurance', 'Finance', 'William Robert Berkley', 'W. R. Berkley Corporation'),
('LDOS', 'Leidos Holdings, Inc.', 'New York Stock Exchange','Information Technology Services', 'Technology Services', 'Roger A. Krone', 'Leidos Holdings, Inc.'),
('FNF', 'Fidelity National Financial, Inc.', 'New York Stock Exchange','Specialty Insurance', 'Finance', 'Raymond R. Quirk', 'Fidelity National Financial, Inc. - FNF Group'),
('ARNC', 'Arconic, Inc.', 'New York Stock Exchange','Aluminum', 'Non-Energy Minerals', 'John C. Plant', 'Arconic, Inc.'),
('ZBRA', 'Zebra Technologies Corp.', 'NASDAQ','Computer Peripherals', 'Electronic Technology', 'Anders Gustafsson', 'Zebra Technologies Corporation Class A'),
('OTEX', 'Open Text Corp.', 'NASDAQ','Packaged Software', 'Technology Services', 'Mark J. Barrenechea', 'Open Text Corporation'),
('RNG', 'RingCentral, Inc.', 'New York Stock Exchange','Packaged Software', 'Technology Services', 'Vladimir G. Shmunis', 'RingCentral, Inc. Class A'),
('EQH', 'AXA Equitable Holdings, Inc.', 'New York Stock Exchange','Financial Conglomerates', 'Finance', 'Mark Pearson', 'AXA Equitable Holdings, Inc.'),
('WST', 'West Pharmaceutical Services, Inc.', 'New York Stock Exchange','Medical Specialties', 'Health Technology', 'Eric Mark Green', 'West Pharmaceutical Services, Inc.'),
('URI', 'United Rentals, Inc.', 'New York Stock Exchange','Finance/Rental/Leasing', 'Finance', 'Matthew John Flannery', 'United Rentals, Inc.'),
('BAH', 'Booz Allen Hamilton Holding Corp.', 'New York Stock Exchange','Miscellaneous Commercial Services', 'Commercial Services', 'Horacio D. Rozanski', 'Booz Allen Hamilton Holding Corporation Class A'),
('DVA', 'DaVita, Inc.', 'New York Stock Exchange','Medical/Nursing Services', 'Health Services', 'Javier J. Rodriguez', 'DaVita Inc.'),
('AZPN', 'Aspen Technology, Inc.', 'NASDAQ','Packaged Software', 'Technology Services', 'Antonio Jose Maeer Pietri', 'Aspen Technology, Inc.'),
('ARCC', 'Ares Capital Corp.', 'NASDAQ','Investment Managers', 'Finance', 'R. Kipp deVeer', 'Ares Capital Corporation'),
('VOYA', 'Voya Financial, Inc.', 'New York Stock Exchange','Life/Health Insurance', 'Finance', 'Rodney Owen Martin', 'Voya Financial, Inc.'),
('AER', 'AerCap Holdings NV', 'New York Stock Exchange','Finance/Rental/Leasing', 'Finance', 'Aengus Kelly', 'AerCap Holdings NV'),
('HUBS', 'HubSpot, Inc.', 'New York Stock Exchange','Information Technology Services', 'Technology Services', 'Brian Patrick Halligan', 'HubSpot, Inc.'),
('FAF', 'First American Financial Corp.', 'New York Stock Exchange','Specialty Insurance', 'Finance', 'Dennis J. Gilmore', 'First American Financial Corporation'),
('HAE', 'Haemonetics Corp.', 'New York Stock Exchange','Medical Specialties', 'Health Technology', 'Christopher A. Simon', 'Haemonetics Corporation'),
('CIEN', 'Ciena Corp.', 'New York Stock Exchange','Telecommunications Equipment', 'Electronic Technology', 'Gary B. Smith', 'Ciena Corporation'),
('ICL', 'ICL-Israel Chemicals Ltd.', 'New York Stock Exchange','Chemicals: Agricultural', 'Process Industries', 'Raviv Zoller', 'ICL-Israel Chemicals Ltd.'),
('INXN', 'InterXion Holding NV', 'New York Stock Exchange','Information Technology Services', 'Technology Services', 'David C. Ruberg', 'Interxion Holding N.V.'),
('ALSN', 'Allison Transmission Holdings, Inc.', 'New York Stock Exchange','Trucks/Construction/Farm Machinery', 'Producer Manufacturing', 'David S. Graziosi', 'Allison Transmission Holdings, Inc.'),
('MDU', 'MDU Resources Group, Inc.', 'New York Stock Exchange','Gas Distributors', 'Utilities', 'David L. Goodin', 'MDU Resources Group Inc'),
('IART', 'Integra LifeSciences Holdings Corp.', 'NASDAQ','Medical Specialties', 'Health Technology', 'Peter J. Arduini', 'Integra LifeSciences Holdings Corporation'),
('BPOP', 'Popular, Inc.', 'NASDAQ','Regional Banks', 'Finance', 'Ignacio Alvarez', 'Popular, Inc.'),
('OMF', 'OneMain Holdings, Inc.', 'New York Stock Exchange','Finance/Rental/Leasing', 'Finance', 'Douglas H. Shulman', 'OneMain Holdings, Inc.'),
('EV', 'Eaton Vance Corp.', 'New York Stock Exchange','Investment Managers', 'Finance', 'Thomas Ewart Faust', 'Eaton Vance Corp.'),
('FHN', 'First Horizon National Corp. (Tennessee)', 'New York Stock Exchange','Regional Banks', 'Finance', 'D. Bryan Jordan', 'First Horizon National Corporation'),
('JBLU', 'JetBlue Airways Corp.', 'NASDAQ','Airlines', 'Transportation', 'Robin Hayes', 'JetBlue Airways Corporation'),
('MTZ', 'MasTec, Inc.', 'New York Stock Exchange','Engineering & Construction', 'Industrial Services', 'José Ramón Mas', 'MasTec, Inc.'),
('ESNT', 'Essent Group Ltd.', 'New York Stock Exchange','Specialty Insurance', 'Finance', 'Mark A. Casale', 'Essent Group Ltd.'),
('RDN', 'Radian Group Inc.', 'New York Stock Exchange','Specialty Insurance', 'Finance', 'Richard G. Thornberry', 'Radian Group Inc.'),
('AWI', 'Armstrong World Industries, Inc.', 'New York Stock Exchange','Building Products', 'Producer Manufacturing', 'Victor D. Grizzle', 'Armstrong World Industries, Inc.'),
('TTEK', 'Tetra Tech, Inc.', 'NASDAQ','Environmental Services', 'Industrial Services', 'Danny Lee Batrack', 'Tetra Tech, Inc.'),
('AGO', 'Assured Guaranty Ltd.', 'New York Stock Exchange','Specialty Insurance', 'Finance', 'Dominic John Frederico', 'Assured Guaranty Ltd.'),
('FTDR', 'frontdoor, Inc.', 'NASDAQ','Homebuilding', 'Consumer Durables', 'Rexford J. Tibbens', 'frontdoor, Inc.'),
('SEDG', 'SolarEdge Technologies, Inc.', 'NASDAQ','Semiconductors', 'Electronic Technology', 'Zvi Lando', 'SolarEdge Technologies, Inc.'),
('AAN', 'Aarons, Inc.', 'New York Stock Exchange','Finance/Rental/Leasing', 'Finance', 'John W. Robinson', 'Aarons, Inc.'),
('FCN', 'FTI Consulting, Inc.', 'New York Stock Exchange','Miscellaneous Commercial Services', 'Commercial Services', 'Steven Henry Gunby', 'FTI Consulting, Inc.'),
('SF', 'Stifel Financial Corp.', 'New York Stock Exchange','Investment Banks/Brokers', 'Finance', 'Ronald James Kruszewski', 'Stifel Financial Corp.'),
('FNB', 'F.N.B. Corp. (Pennsylvania)', 'New York Stock Exchange','Regional Banks', 'Finance', 'Vincent J. Delie', 'F.N.B. Corporation'),
('UMPQ', 'Umpqua Holdings Corp.', 'NASDAQ','Regional Banks', 'Finance', 'Cort Lane OHaver', 'Umpqua Holdings Corporation'),
('JJSF', 'J&J Snack Foods Corp.', 'NASDAQ','Food: Specialty/Candy', 'Consumer Non-Durables', 'Gerald B. Shreiber', 'J & J Snack Foods Corp.'),
('LM', 'Legg Mason, Inc.', 'New York Stock Exchange','Investment Managers', 'Finance', 'Joseph Andrew Sullivan', 'Legg Mason, Inc.'),
('GLOB', 'Globant SA', 'New York Stock Exchange','Information Technology Services', 'Technology Services', 'Martín Migoya', 'Globant SA'),
('ENPH', 'Enphase Energy, Inc.', 'NASDAQ','Semiconductors', 'Electronic Technology', 'Badrinarayanan Kothandaraman', 'Enphase Energy, Inc.'),
('FII', 'Federated Investors, Inc.', 'New York Stock Exchange','Investment Managers', 'Finance', 'John Christopher Donahue', 'Federated Investors, Inc. Class B'),
('CRUS', 'Cirrus Logic, Inc.', 'NASDAQ','Semiconductors', 'Electronic Technology', 'Jason P. Rhode', 'Cirrus Logic, Inc.'),
('MEDP', 'Medpace Holdings, Inc.', 'NASDAQ','Miscellaneous Commercial Services', 'Commercial Services', 'August James Troendle', 'Medpace Holdings, Inc.'),
('HLI', 'Houlihan Lokey, Inc.', 'New York Stock Exchange','Investment Banks/Brokers', 'Finance', 'Scott Lee Beiser', 'Houlihan Lokey, Inc. Class A'),
('WAFD', 'Washington Federal, Inc.', 'NASDAQ','Savings Banks', 'Finance', 'Brent Joseph Beardall', 'Washington Federal, Inc.'),
('CATY', 'Cathay General Bancorp', 'NASDAQ','Regional Banks', 'Finance', 'Pin Tai', 'Cathay General Bancorp'),
('FULT', 'Fulton Financial Corp.', 'NASDAQ','Regional Banks', 'Finance', 'E. Philip Wenger', 'Fulton Financial Corporation'),
('BAC', 'Bank of America Corp.', 'New York Stock Exchange','Major Banks', 'Finance', 'Brian T. Moynihan', 'Bank of America Corp'),
('BHC', 'Bausch Health Cos., Inc.', 'New York Stock Exchange','Pharmaceuticals: Other', 'Health Technology', 'Joseph C. Papa', 'Bausch Health Companies Inc.'),
('DFS', 'Discover Financial Services', 'New York Stock Exchange','Regional Banks', 'Finance', 'Roger C. Hochschild', 'Discover Financial Services'),
('ENTG', 'Entegris, Inc.', 'NASDAQ','Electronic Production Equipment', 'Electronic Technology', 'Bertrand Loy', 'Entegris, Inc.'),
('FENY', 'Fidelity MSCI Energy Index ETF', 'NYSE Arca','Investment Trusts/Mutual Funds', 'Miscellaneous', '', 'Fidelity MSCI Energy Index ETF'),
('FHLC', 'Fidelity MSCI Health Care Index ETF', 'NYSE Arca','Investment Trusts/Mutual Funds', 'Miscellaneous', '', 'Fidelity MSCI Health Care Index ETF'),
('FITB', 'Fifth Third Bancorp', 'NASDAQ','Regional Banks', 'Finance', 'Gregory D. Carmichael', 'Fifth Third Bancorp'),
('FREL', 'Fidelity MSCI Real Estate Index ETF', 'NYSE Arca','Investment Trusts/Mutual Funds', 'Miscellaneous', '', 'Fidelity MSCI Real Estate Index ETF'),
('FUTY', 'Fidelity MSCI Utilities Index ETF', 'NYSE Arca','Investment Trusts/Mutual Funds', 'Miscellaneous', '', 'Fidelity MSCI Utilities Index ETF'),
('GM', 'General Motors Co.', 'New York Stock Exchange','Motor Vehicles', 'Consumer Durables', 'Mary Teresa Barra', 'General Motors Company'),
('HUM', 'Humana, Inc.', 'New York Stock Exchange','Managed Health Care', 'Health Services', 'Bruce Dale Broussard', 'Humana Inc.'),
('IGLB', 'iShares Long-Term Corporate Bond ETF', 'NYSE Arca','Investment Trusts/Mutual Funds', 'Miscellaneous', '', 'iShares Long-Term Corporate Bond ETF'),
('IJR', 'iShares Core S&P Small Cap ETF', 'NYSE Arca','Investment Trusts/Mutual Funds', 'Miscellaneous', '', 'iShares Core S&P Small Cap ETF'),
('INTC', 'Intel Corp.', 'NASDAQ','Semiconductors', 'Electronic Technology', 'Robert Holmes Swan', 'Intel Corporation'),
('PFE', 'Pfizer Inc.', 'New York Stock Exchange','Pharmaceuticals: Major', 'Health Technology', 'Albert Bourla', 'Pfizer Inc.'),
('ROST', 'Ross Stores, Inc.', 'NASDAQ','Apparel/Footwear Retail', 'Retail Trade', 'Barbara Rentler', 'Ross Stores, Inc.')